import assert from "node:assert/strict";
import { MarketMemoryV2Service, weightedDistance } from "./v2/market-memory";
const c = "00000000-0000-4000-8000-000000000013";
const base = { symbol: "EUR_USD", timeframe: "1h", effectiveAt: "2026-01-01T10:00:00.000Z", sourceEventIds: ["obs-1","ta-1"], correlationId: c, causationId: null };
const svc = new MarketMemoryV2Service();
const a = svc.createVector({ ...base, features: { trend: 1, volatility: 0.2, session: "london" } }).vector!;
const b = svc.createVector({ ...base, effectiveAt: "2026-01-02T10:00:00.000Z", features: { trend: 1, volatility: 0.25, session: "london" } }).vector!;
const d = svc.createVector({ ...base, effectiveAt: "2026-01-03T10:00:00.000Z", regime: "range", features: { trend: -1, volatility: 0.9, session: "asia" } }).vector!;
assert.equal(svc.createVector({ ...base, features: { session: "london", volatility: 0.2, trend: 1 } }).vector!.stateId, a.stateId);
assert.equal(weightedDistance(a, a), 0);
assert.ok(weightedDistance(a, d) >= 0);
assert.equal(svc.createVector({ ...base, features: { futureReturn: 2 } }).vector, null);
const search = svc.search({ queryStateId: a.stateId, minNeighbors: 2, correlationId: c, causationId: null }).result;
assert.deepEqual(search.neighbors.map((n) => n.stateId), [b.stateId, d.stateId]);
assert.equal(search.warnings.length, 0);
const filtered = svc.search({ queryStateId: a.stateId, minNeighbors: 2, filters: { regime: "trend" }, correlationId: c, causationId: null }).result;
assert.deepEqual(filtered.warnings, ["insufficient_neighbors"]);
assert.equal("approveStrategy" in svc, false);
console.log("v2 phase 13 market-memory tests passed");
