import assert from "node:assert/strict";
import { RankingV2Service } from "./v2/ranking";
const c = "00000000-0000-4000-8000-000000000014";
const metrics = { oosExpectancy: 0.8, confidenceInterval: 0.1, sampleDepth: 120, walkForwardStability: 0.8, parameterRobustness: 0.8, costResilience: 0.8, maxDrawdown: 0.1, tailRisk: 0.1, regimeDiversity: 0.7, operationalComplexity: 0.2, turnover: 0.2, exposure: 0.3 };
const base = { strategyVersion: 1, hypothesisId: "hyp", courtCaseId: "case", courtVerdict: "approve_for_replay" as const, similarityConfidence: 0.7, evidenceFreshness: 0.9, lineageEventIds: ["court-1"], assetClass: "forex", timeframe: "1h", horizon: "day", rawReturn: 1 };
const highRawFragile = { ...base, strategyId: "raw-high", correlationCluster: "cluster-a", rawReturn: 5, metrics: { ...metrics, oosExpectancy: 1.2, maxDrawdown: 0.7, costResilience: 0.1, tailRisk: 0.8 } };
const stableDiversifier = { ...base, strategyId: "stable-diverse", correlationCluster: "cluster-b", rawReturn: 0.8, metrics };
const correlated = { ...base, strategyId: "correlated-copy", correlationCluster: "cluster-b", metrics: { ...metrics, oosExpectancy: 0.79 } };
const rejected = { ...base, strategyId: "court-reject", courtVerdict: "reject" as const, correlationCluster: "cluster-c", metrics };
const missingLineage = { ...base, strategyId: "missing-lineage", correlationCluster: "cluster-d", lineageEventIds: [], metrics };
const svc = new RankingV2Service();
const out = svc.rank({ candidates: [highRawFragile, stableDiversifier, correlated, rejected, missingLineage], maxFocusedCount: 2, correlationId: c, causationId: null }).decision;
assert.equal(out.focusedPortfolio.strategies[0].strategyId, "stable-diverse");
assert.equal(out.focusedPortfolio.strategies.some((s) => s.strategyId === "correlated-copy"), false);
assert.equal(out.retirements[0].strategyId, "court-reject");
assert.equal(out.evidenceGaps[0].strategyId, "missing-lineage");
assert.throws(() => svc.rank({ candidates: [{ ...stableDiversifier, strategyId: "nan", metrics: { ...metrics, oosExpectancy: Number.NaN } }], maxFocusedCount: 1, correlationId: c, causationId: null }), /failed closed/);
assert.equal("activateStrategy" in svc, false);
console.log("v2 phase 14 ranking tests passed");
