export const OrchestrationV2EventTypes = {
  ResearchCycleRequested: "ResearchCycleRequested",
  ResearchCycleStarted: "ResearchCycleStarted",
  ResearchCycleCheckpointed: "ResearchCycleCheckpointed",
  ResearchCycleCompleted: "ResearchCycleCompleted",
  ResearchCycleFailed: "ResearchCycleFailed",
  ResearchCycleCancelled: "ResearchCycleCancelled",
  OrchestrationEventRouted: "OrchestrationEventRouted",
  OrchestrationEventRejected: "OrchestrationEventRejected",
  ConsumerExecutionStarted: "ConsumerExecutionStarted",
  ConsumerExecutionCompleted: "ConsumerExecutionCompleted",
  ConsumerExecutionFailed: "ConsumerExecutionFailed",
  ConsumerRetryScheduled: "ConsumerRetryScheduled",
  DeadLetterEventCreated: "DeadLetterEventCreated",
  PoisonEventQuarantined: "PoisonEventQuarantined",
  CircuitBreakerOpened: "CircuitBreakerOpened",
  CircuitBreakerClosed: "CircuitBreakerClosed",
  WorkerLeaseAcquired: "WorkerLeaseAcquired",
  WorkerLeaseExpired: "WorkerLeaseExpired",
  WorkerLeaseRecovered: "WorkerLeaseRecovered",
} as const;
