import { randomUUID } from "crypto";
import type { MarketObservation, ObservationDetector, ObservationInput } from "../contracts";
import { evidenceFingerprint, scoreObservation, semanticObservationKey } from "../evidence";

export const liquiditySweepDetector: ObservationDetector = {
  detectorId: "liquidity-sweep",
  detectorVersion: "observation-detector.v1",
  capability: { detectorId: "liquidity-sweep", detectorVersion: "observation-detector.v1", strategyFamily: "liquidity_reversal", supportedTimeframes: ["5m", "15m", "30m", "1h"], requiredCandles: 50, requiredFields: ["open", "high", "low", "close"], minimumDataQuality: 0.55, enabled: true },
  detect(input: ObservationInput): MarketObservation[] {
    const support = input.evidence.filter((item) => item.fact === "liquidity.sweep" && item.value === true);
    if (!support.length) return [];
    const scored = scoreObservation(input, support, input.contradictoryEvidence ?? []);
    const evidence = support.map(item => ({ ...item, symbol: input.symbol, timeframe: input.timeframe, detectorId: liquiditySweepDetector.detectorId, detectorVersion: liquiditySweepDetector.detectorVersion, observationType: "liquidity_sweep", candleStart: input.candleStart, candleEnd: input.candleEnd, marketDataSource: input.marketDataSource, sourceDataIds: input.sourceDataIds, sourceDataHash: input.sourceDataHash, detectorParameters: input.detectorParameters, evidenceId: evidenceFingerprint([{ ...item, symbol: input.symbol, timeframe: input.timeframe, detectorId: liquiditySweepDetector.detectorId, detectorVersion: liquiditySweepDetector.detectorVersion, observationType: "liquidity_sweep", candleStart: input.candleStart, candleEnd: input.candleEnd, marketDataSource: input.marketDataSource, sourceDataIds: input.sourceDataIds, sourceDataHash: input.sourceDataHash, detectorParameters: input.detectorParameters }]) }));
    const naturalKey = semanticObservationKey({ symbol: input.symbol, timeframe: input.timeframe, detectorId: liquiditySweepDetector.detectorId, detectorVersion: liquiditySweepDetector.detectorVersion, observationType: "liquidity_sweep", candleStart: input.candleStart, candleEnd: input.candleEnd, sourceDataHash: input.sourceDataHash, detectorParameters: input.detectorParameters });
    return [{ observationId: randomUUID(), schemaVersion: "fincoach.v2.observation.1", symbol: input.symbol, timeframe: input.timeframe, observationType: "liquidity_sweep", detectorId: liquiditySweepDetector.detectorId, detectorVersion: liquiditySweepDetector.detectorVersion, strategyFamily: liquiditySweepDetector.capability?.strategyFamily, observedAt: input.observedAt, candleStart: input.candleStart, candleEnd: input.candleEnd, lookbackStart: input.lookbackStart, lookbackEnd: input.lookbackEnd, marketDataSource: input.marketDataSource, sourceDataIds: input.sourceDataIds, sourceDataHash: input.sourceDataHash, inputSnapshotId: input.inputSnapshotId, detectorParameters: input.detectorParameters, naturalKey, idempotencyKey: naturalKey, metrics: input.metrics, effectiveFrom: input.observedAt, expiresAt: new Date(Date.parse(input.observedAt) + 30 * 60_000).toISOString(), evidence, contradictoryEvidence: input.contradictoryEvidence ?? [], confidence: scored.confidence, qualityScore: scored.qualityScore, scoreComponents: scored.scoreComponents, contextEventId: input.contextEventId, upstreamEventIds: input.upstreamEventIds, correlationId: input.correlationId, causationId: input.causationId, lifecycle: "active", supersedesId: null }];
  },
};
